    name: Go

    env:
        GIN_MODE: release
        GOROOT: "/opt/hostedtoolcache/go/1.23.0/x64"
        minGoVersion: 1.23
        buildTags: 
        checks: inherit
        format: text

    on:
      push:
        branches: [ "main" ]
      pull_request:
        branches: [ "main" ]

    jobs:
      build:
        runs-on: ubuntu-latest

        permissions:
          checks: write

        steps:
        - uses: actions/checkout@v3

        - name: Set up Go
          uses: actions/setup-go@v3
          with:
            go-version: '1.23'
            cache: true

        - name: Configure Go environment
          run: |
            export GOROOT="/opt/hostedtoolcache/go/1.23.0/x64"
            export GOPATH="$(go env GOPATH)"
            echo "GOROOT is set to: $GOROOT"
            echo "GOPATH is set to: $GOPATH"
          shell: bash    

        - name: Revive Action
          uses: morphy2k/revive-action@v2.4.1

        - name: Staticcheck
          run: |
            export STATICCHECK_CACHE="/home/runner/work/_temp/staticcheck"
            go install honnef.co/go/tools/cmd/staticcheck@v0.4.3
            $(go env GOPATH)/bin/staticcheck -tags "${buildTags}" -checks "${checks}" -f "${format}" -go "${minGoVersion}" ./...
         

        - name: Build
          run: |
            go mod download
            go install gotest.tools/gotestsum@latest

        - name: Test
          run: |
            gotestsum --format=standard-verbose --junitfile=junit.xml

        - name: Publish Test Report
          uses: mikepenz/action-junit-report@v3
          if: success() || failure() # always run even if the previous step fails
          with:
            report_paths: '**/junit.xml'
            detailed_summary: true
            include_passed: true
